version: '3.7'
services:
  tarsnap:
    init: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    image: johnthenerd/tarsnap
    healthcheck:
      test: ps aux | grep cron | grep -v grep
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      TZ: America/St_Johns
    volumes:
      - /cache:/cache
      - /backup:/backup:ro
    secrets:
      - tarsnap
secrets:
  tarsnap:
    external: true
